### ISSUE TITLE
All page screenshot doesn't work on specific URL

### ISSUE THREAD

**Issue by b-chan** [Aminadav/screenshot-extension#102]
Hi team, thanks for taking a look at this. 

The All-Page Screenshot doesn't work on the following page: 
https://app.elev.io/kb

It only captures a Visible Screenshot.

**Comment by Fight4freeTech** [comment]
Similar Google Chrome updated and wouldn't work unless I clicked allow something... Now there are some pages that I cant get to give a full screenshot mostly news webpages but also a biblical studies page... Pages ( all of the http://biblehub.com and all of the www.i24news.tv/en pages don't work. but also a couple of the other news print pages also wont fully print screen )

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.

**Comment by musca001** [comment]
It's not fixed. I just installed 1Click and it only saves the visible area even when selecting whole page. This is OSX Mohave with Chrome Version 71.0.3578.30 (Official Build) beta (64-bit)
