### ISSUE TITLE
load_cropper_without_selection is not defined

### ISSUE THREAD

**Issue by Dartanjan** [Aminadav/screenshot-extension#9]
When I try to use the region crop tool, nothing happens. This is what shows up in the Console:

Uncaught ReferenceError: load_cropper_without_selection is not defined
(anonymous function) @ VM437:1

Any resolution to this?

**Comment by Aminadav** [comment]
It should be fixed. Please test the last version.

**Comment by constantin-iliescu** [comment]
Just installed the extension freshly updated chrome and the issue is still there:

Uncaught ReferenceError: load_cropper_without_selection is not defined
(anonymous) @ VM73:1
