### ISSUE TITLE
Open Screenshot does not appear to request file URL access, despite instructions

### ISSUE THREAD

**Issue by ferdnyc** [Aminadav/screenshot-extension#96]
Using Google Chrome Version 61.0.3163.79 (Official Build) (64-bit) under Linux, with Open Screenshot 24.0 installed from the Chrome Store, when the extension is activated on a `file:///` URL the pop-up pane contains the instruction:
> Go to chrome://extensions, and check the box "Allow access to file URLs"

(Formatted with blue underlined text and appearing to be a link, but it does not respond to clicks.)
Problem is, after manually navigating to Extensions, the file-URL checkbox is not present on Open Screenshot. 
![screenshot from 2017-09-12 03-50-34](https://user-images.githubusercontent.com/538020/30314152-d36fda6c-976d-11e7-808a-0a8e6dc04216.png)
Compare to Stylish, which does request permission to access `file:///` URLs.

**Comment by DyaniPerson** [comment]
I also have this issue. 
![image](https://user-images.githubusercontent.com/17993136/31903414-3fb7139c-b7e5-11e7-9fd2-ea355fcba6f2.png)

**Comment by Aminadav** [comment]
Please test the last version, it should be fixed.

**Comment by ferdnyc** [comment]
No, no it's not fixed. In fact, things are worse than ever. 

Now there's a "Settings" button in the extension menu that _does nothing_ (see how there's no "Options" link anymore, in the Extension listing), plus there's _*still*_ no sign of it requesting File-access permissions.

![screenshot from 2018-02-14 13-08-48](https://user-images.githubusercontent.com/538020/36220398-69b4997e-1188-11e8-9534-cdb42174ba79.png)

**Comment by ferdnyc** [comment]
Looking at the Settings issue, the problem there appears to be that `settings.js` is included in `background.html` — but there's no `settings.js` file included with the extension.
![screenshot from 2018-02-14 13-36-58](https://user-images.githubusercontent.com/538020/36221515-4a75d326-118c-11e8-940b-c68917e163eb.png)
